// laravel_10_breeze_inertia_vue/resources/js/Pages/Post/Create.vue
<template>
    <div class="container">
        <br>
        <Link
        :href="route('posts.index')"
        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded my-3 text-white"
        >post List</Link
    > <br> <br> <br>
  <form @submit.prevent="submit" class="form">
                            <div class="mb-4 form-group">
                                <label 
                                    for="title" 
                                    class="block text-gray-700 text-sm font-bold mb-2">
                                    Title:</label>
                                <input 
                                    type="text" 
                                    class="form-control" 
                                    placeholder="Enter Title" 
                                    id="title"
                                    v-model="form.title" />

                            </div>

                            <div class="mb-4 form-group">
                                <label 
                                    for="body" 
                                    class="block text-gray-700 text-sm font-bold mb-2">
                                    Body:</label>
                                <textarea 
                                    class="form-control" id="body" 
                                    v-model="form.body" 
                                    placeholder="Enter Body"></textarea>
                            </div>

                            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded my-3 text-white">
                                Submit
                            </button>

                        </form>
                    </div>
</template>

<script setup>
import { useForm, Link } from '@inertiajs/vue3';
const form = useForm({
    title: '',
    body: '',

});
const submit = () => {
  form.post("/posts");
};
</script>

<style>

</style>

// laraval_react_crud/resources/js/Pages/Posts/Create.jsx
import React from 'react';
import { useForm } from '@inertiajs/react';

export default function Create(){

    const { data, setData, post , errors } =useForm({
    title:"",
    body:""

})

    function handleSubmit(e){
        e.preventDefault();
        post(route('posts.store'))
       
    }

  return (
    <div>
        <h1>Post entry</h1>
        <form onSubmit={handleSubmit}>
            Title: <input type="text" name="title" placeholder="Enter Title" value={data.title} onChange={(e)=>setData('title',e.target.value)}/> <span>{errors.title}</span> <br />
            Details: <textarea name="body" placeholder="Enter Details" onChange={(e)=>setData('body',e.target.value)}>{data.body}</textarea><span>{errors.body}</span> <br />
            <button type='submit' name='submit'>Submit</button>

        </form>

    </div>
  )
}
